### ISSUE TITLE
Potential Bug? "Back" returns to page 1

### ISSUE THREAD

**Issue by meremaines** [sketch-city/harvey-api#104]
Idea from Cheryl:

After a user submits an update to any record, the record's summary page shows three links at the bottom: update, back, and archive. After clicking "back," users expect to return to the most recently viewed page of the list, but instead, "back" returns you to the very first page of the list, requiring you to click through all the pages again to pick up where you left off.

**Comment by rogerroelofs** [comment]
This is fixed in the irma repo it is just adding 'saveState' to app/views/shared/_table.html.erb

**Comment by jwo** [comment]
I think back-merging the saveState from irma-api is the right way to go for all of our endpoints in v1 (and also then in v2)

**Comment by rogerroelofs** [comment]
saveState may be doing more than we really need since it also saves the column info and we don't allow users to hide / show columns.  See https://github.com/Irma-Response/irma-api/pull/43 for updates that might be useful.
