### ISSUE TITLE
Per Field Change Tracking 

### ISSUE THREAD

**Issue by jnolasco** [sketch-city/harvey-api#107]
Longer term item. Create a structure that has an aggregate static schema for a shelter like this:

[shelters]
id
name
address
is_full

and an update queue like this
[shelter_updates]
id
shelter_id
field -- name|address|is_full)
payload -- the contents of the new field
timestamp
admin_id -- whoever put this update in

This would turn shelters into more of a cache of all the most recent values set in shelter_updates. After every update, "recompile" the record in shelters. You could track and revert changes as well as allow for more granular changes that don't impact the whoel record.

**Comment by ironcoconut** [comment]
The long term goal is to move everything to v2 once the immediate need for relief calms down. See the roadmap issue.

If we want to keep a log of changes, we can add the  paper trail gem that was suggested by @dorton in the beginning.

https://github.com/airblade/paper_trail

**Comment by jwo** [comment]
@jnolasco Going to close in favor of #103 because that has the reason why users want the feature.
