### ISSUE TITLE
Emit shelter id in api/v1/shelters

### ISSUE THREAD

**Issue by jnolasco** [sketch-city/harvey-api#108]
Can we emit the shelterid in api/v1/shelter? It would allow houstonshelters.org to to create links back to api.harveyneeds.org for direct editing of shelter statuses.

**Comment by jwo** [comment]
@jnolasco I'll ping you when this is live

**Comment by jnolasco** [comment]
Thank you!

**Comment by jnolasco** [comment]
fwiw, irmashelters has this already applied, but it may just be easier to add it to the json quick and resolve any tiny conflict (with an eventual big merge) later

**Comment by jwo** [comment]
@jnolasco this is live on the harvey needs API
