### ISSUE TITLE
TODO: Update readme with ids

### ISSUE THREAD

**Issue by jwo** [sketch-city/harvey-api#114]
We recently started to emit ids on api endpoints. We should update the readme example to include they.

**Comment by cmacaulay** [comment]
@jwo I'm happy to help here! Just to make sure - the readme needs to be updated to include id's on the JSON examples?

**Comment by jwo** [comment]
@cmacaulay Awesome, thanks! 

Yep, that's all we need, just IDs on each of the examples in the readme. You can even make up the ids, like "264456"

```json
  "id": 264534,
   ... existing here
```
