### ISSUE TITLE
TODO: Add delete with confirmation for need and shelter

### ISSUE THREAD

**Issue by jwo** [sketch-city/harvey-api#19]
For administrators, be able to delete needs and shelters. 

The button should show on the `show` page, with a data-confirmation of "Are you Sure?"

We should have tests that make sure that a non-admin cannot delete the entities.

**Comment by ironcoconut** [comment]
Remove from DB or add a deleted_by field and hide them from the api and tables?

**Comment by dorton** [comment]
I just did an active boolean and hid from tables.  Prolly need to also hide on api.

**Comment by jwo** [comment]
closed with #24
