### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ironcoconut** [sketch-city/harvey-api#2]
After discussing with @neerajt and co., we have settled on the following roadmap for the API.

### Immediate Goals (next 1-3 days)

1. Incorporation Individual needs spreadsheet into API (being build by Will) (API)
2. Deploy front end for data entry for shelters, needs and individual needs (Frontend)
3. Deprecate the google sheet (Neeraj?/Marketing?)

### Long Term Goals (next week or so)

1. Migrate database to a more sustainable schema with tables for: locations, needs, offers, volunteers, refugees, tags, etc... (API)
2. Build v2 of the api (or update v1 to match new schema) (API)
2. Update data entry to match new schema (Frontend)
3. Make front end prettier (Frontend)
3. Add real time indicators to frond end to provide feedback to the volunteers. Widget that show shelters needing updates, pending updates, users on site, etc... (Frontend)

## Plan of Action

1. Divide into 2 teams: API and frontend
2. Ben will nominally lead frontend. Jessi will nominally lead API.

The hope is that the 2 teams can work in parallel to maximize productivity.

**Comment by brooklynrob** [comment]
By "individual needs", this means the individual needs of single shelters? Or the needs of individual people/families? If latter probably want to think about privacy concerns of putting in a public API. I am guessing it's the former.

**Comment by brooklynrob** [comment]
Re "Deprecate the google sheet", I assume the approach would be to leave the current tables as legacy tables from the cutover, and then run a job to migrate the data from those tables to the new schema / newly added tables?

With a little work we could probably also develop a routine that pulls from the legacy tables populated by the google doc data such that if needed one could do incremental updates from the google doc (i.e., if someone added data there after cutover; or if there was some reason to want to keep the sheet as a place for importing data available as an option) while having already migrated to the new database as the system of record. 

And has there been any thought of going the other way? To populate data out from the database to a google sheet for people who like that interface?

**Comment by ironcoconut** [comment]
Individual people. Shelters are on the shelters table. Non-shelter groups basically represented by needs. Individual needs are individual people. Though individuals are doing something with facebook now. Check with Will if you want more details on that effort.

**Comment by ironcoconut** [comment]
We have a job that migrates the data from the sheets. That is the basis of how the api functions. See the readme for how to set that up locally. 

The google sheet has mad limitations and all are eager to move away from it. Ping Jeff or Neeraj for details.

Also, this plan is being executed atm. Immediate goals are almost finished. We are figuring out the db schema in the slack as we speak.

**Comment by neerajt** [comment]
@brooklynrob for your last point 

> And has there been any thought of going the other way? To populate data out from the database to a google sheet for people who like that interface?

Do you mean google sheets for consumption for app-developers? Or do you mean google sheets as an interface for volunteer updates to the data?

For consumption by app developers, I hadn't thought about that much. The app developers we talked to seem to strongly prefer the API worked on by @jwo and @crertel.

For an interface for volunteer updates, google sheets is badass in a bunch of ways. The issue really came down to two things: 1) a technical limit on the number of people feeding in data (max 50 editors on a google sheet) and 2) validating changes to the data set as more and more people began to rely on it

**Comment by brooklynrob** [comment]
@ironcoconut 
> Individual people. Shelters are on the shelters table. Non-shelter groups basically represented by needs. Individual needs are individual people. 

Just calling out a more non-technical consideration. I don't to what degree the taxonomy of an "individual need" has been defined -- i.e., what fields about a individual are going to be collected. 

I don't see a same of similar concept of an individual need either in r 1) the existing GSheet we're migrating from or 2) the first cut of the database design. But if the intention is to collect, say, last names, street addresses, and then tie that with a need - and then in turn expose that on a public API anyone in the world can see - you may want to run that by whomever is doing the gut-check legal reviews as that's PID (personally identifiable information) that you're then distributing publicly.

As context I was involved in a similar effort to what is being done in Houston in NYC during Sandy and we had to deal with similar issues. There are additional issues of where the legal liability would lie, but first thing is probably just to have a discussion to affirm you're comfortable not only collecting and holding this sort of info, but in turn distributing it. 

I'm also guessing that there are lot of people who may have needs that may be undocumented. This makes this discussion even more important, especially if you're collecting and distributing names and addresses.

**Comment by jwo** [comment]
@ironcoconut Much of immediate is complete, and @cmason is handling the connect (individual needs) stuff... is this roadmap still applicable? Can we close if not?

**Comment by neerajt** [comment]
@ironcoconut @jwo this is an excellent write-up and I'm bookmarking it for posterity & future study :)

That said, it looks like we've graduated past this now. Vote to close.

**Comment by ironcoconut** [comment]
Amazing to come so far.
