### ISSUE TITLE
TODO: Force SSL in production mode

### ISSUE THREAD

**Issue by jwo** [sketch-city/harvey-api#26]

**Comment by ajclose** [comment]
I looked into the production environment config file and config.force_ssl is already set to true.   I checked in the browser and it is already using https.  Is there anything else that needs to be done?

**Comment by jwo** [comment]
@ajclose eek, looks like I fixed and didn't remember fixing :)

git blame says it was me: 

```
b33a3daa (Jesse Wolgamott 2017-09-03 12:52:48 -0500 48)
```
