### ISSUE TITLE
TODO Fix geocoding on models

### ISSUE THREAD

**Issue by ironcoconut** [sketch-city/harvey-api#28]
We had an emergency fix here: https://github.com/sketch-city/harvey-api/pull/25

This issue serves to remind us that automatic geocoding is disable for the moment.

Ideally geocoding should occur automatically. Determine for models:

- If sufficient address information exists to geocode automatically and consistently.
- Enable geocoding where possible.

This may not be possible until we migrate the DB to a better schema.

**Comment by tbarn** [comment]
Is there any way this is preventing us from entering new lat/long on needs? 

For example, I was unable to added a lat/long to this listing: https://api.harveyneeds.org/needs/8330. I wasn't sure if it was on the API side or something client side.

**Comment by jwo** [comment]
@tbarn you should be able to manually enter lat/lon when creating/updating needs and shelters. If you can't, we need to fix

**Comment by tbarn** [comment]
Yeah, that's what I was doing. I'd click "save" and it wasn't saving it. I didn't see any console errors either.

**Comment by jwo** [comment]
for geocoding --- we can either :
* use browser geocoder and show a map with a pin as they are entering an address. Gives a visual cue and could have address completion. 
* use geocoder on the back end after. Less change to the UI

**Comment by tbarn** [comment]
I think for the second case, there will need to be a good way to deal with incomplete or bad addresses. 

There's probably a few different errors it could get, will need to think through dealing with them to make it easiest for the submitter.

A common thing I've seen is, some include a city and some don't. And that address could exist in multiple cities so hard to know which. In Shelters, I am not sure if City is a required field, but in Needs it doesn't exist right now.

**Comment by jwo** [comment]
@tbarn Agree, I think the first way is probably the way that is the clearest to users (and easiest on servers)

**Comment by tbarn** [comment]
Yeah, it is a bit more UI and frontend work, but might cause less issues in the end and less confusion to users. Is there a place y'all are tracking and planning this kind of work outside of Slack?

**Comment by user512** [comment]
I might be able to hack something temporary for the browser geocode approach tonight after work (never work on map before but happy to learn). But feel free to let me know if you are already working on it, happy to pick up another task.

**Comment by tdooner** [comment]
We could just update the address field to be a Google Places Autocomplete (or add another field), which I think would give us a benefit of also having a stable ID for a given place that would be also usable with other Google Maps APIs.

**Comment by jwo** [comment]
@tdooner I that's a perfect idea; I had thought of using the places autocomplete to get a lat/lng (and display on a map as they're entering), but not of storing the google placed id.

that's fantastic
