### ISSUE TITLE
Sync with the Google Doc

### ISSUE THREAD

**Issue by rmoscowitz** [sketch-city/harvey-api#29]
We need a solution for keeping the Google Doc in sync with the database. Volunteers are still making changes in the spreadsheet (including lots from Saturday afternoon).

One option would be to take a back up of the current database, enable the sync to get today's changes, then manually diff the back up with the updated database.

**Comment by ironcoconut** [comment]
It really is best to have them move to the website. We did not plan to have both running at the same time. I don't know if we have the dev resources to do that diff in a timely manner.

**Comment by rmoscowitz** [comment]
What about pg_dump to text files? I can do the diff and manually re-enter any updates from yesterday that will get wiped.

**Comment by rmoscowitz** [comment]
I just have a feeling there are too many changes in the Google Doc now to _not_ do one more import.

Totally open to other ideas, I just want to make sure all of the volunteer work yesterday doesn't disappear into the internet void.

**Comment by ironcoconut** [comment]
I understand. If you can do that, it would be great.

You can also get current data from the api directly.

@jwo how hard is it to get a data dump?

**Comment by rmoscowitz** [comment]
Ah that's true, and way easier! I can just save the json file.

**Comment by ironcoconut** [comment]
Awesome!

**Comment by rmoscowitz** [comment]
I'm backing up responses from /api/v1/shelters and /api/v1/needs every 30 minutes. If someone does the import from Google, let me know and I'll take care of the diff.

**Comment by ironcoconut** [comment]
AFAIK the google sheet is dead. Has the DB been manually updated yet?

**Comment by rmoscowitz** [comment]
@ironcoconut Sorry I was offline for several hours. It looks like the import from the Google Doc was successful. (The only strange thing I've noticed so far is that all of the lat/longs changed... I don't know which ones are accurate so I'm leaving them alone.)

I'm working on finding the updates that were wiped now and manually re-entering them. This issue can be closed. Thanks again for your help!

**Comment by ironcoconut** [comment]
Awesome. Thank you. I believe you deserve a medal for data entry!
