### ISSUE TITLE
Shelters/Needs Pages Not Updating

### ISSUE THREAD

**Issue by rmoscowitz** [sketch-city/harvey-api#30]
After an admin makes a change or approves something in the queue, the /shelters and /needs pages are not reflecting the updates.

Volunteers reporting that the admin updates _are_ visible on the maps.

**Comment by ironcoconut** [comment]
They would need to refresh the page to see the updates.

It is more than likely a caching issue. The browser is storing all the data locally. 

We need to setup a mechanism to force updates on the table. It is not live like Google sheets.

**Comment by rmoscowitz** [comment]
Take a look at the Shelters page and sort by "Last Updated". People were trying to make updates yesterday evening, but it shows the most recent update was yesterday at 1:30PM. 

Doesn't look like caching. Is it possible there's a limit on responses getting to the browser?

**Comment by ironcoconut** [comment]
Is the field name last updated? That field is set manually.

We are not displaying updated at, which is set when the record is updated last automatically.

Is the information in the table correct, regardless of the updated field?

**Comment by ironcoconut** [comment]
@rmoscowitz are the explanations of this issue satisfactory? If so can we close it? Or is there still a bug that needs to be resolved? 

I collected all the UI issues I am aware of here: https://github.com/sketch-city/harvey-api/issues/31

**Comment by rmoscowitz** [comment]
@ironcoconut Ah I understand! We were expecting "Last Updated" to auto update. I checked again and yes, the fields that are actually being changed are saved. Thanks for explaining, this can be closed.

**Comment by ironcoconut** [comment]
Great. Happy labor day.
