### ISSUE TITLE
TODO: Add contributors page in public front end

### ISSUE THREAD

**Issue by jwo** [sketch-city/harvey-api#34]
Could be cool to have a contributors page which fetches data from the GitHub API and outputs their avatar, name, and github handle on the API page.

A nice way to say thanks.

Example (in WP) of what I mean: http://underscores.me/ and writeup: https://konstantin.blog/2012/how-to-get-a-list-of-contributors-from-a-github-project/

**Comment by wabbit983** [comment]
Not sure how you want me to push this to you. I don't know ruby, but I wrote this in JS with some html and css...

http://digitalwabbit.com/contributors.html

**Comment by jwo** [comment]
Went live!
