### ISSUE TITLE
TODO: Add feedback for workers

### ISSUE THREAD

**Issue by ironcoconut** [sketch-city/harvey-api#38]
Via sockets, we want the following live updates:

1. Show when there are pending updates on a table (step 1, almost done by jwo https://github.com/sketch-city/harvey-api/pull/36)
2. Update table in realtime via sockets using Datatables API
3. Display stats concerning:
  - Number of users on the site
  - Number of Updates pending in the queue
  - Number of stale records (a record is stale when: there is no pending draft update and the record has not been updated in > 1 day)
  - The status of each record in the table (Current, Stale, Waiting Approval, Being Updated)

**Comment by jwo** [comment]
closing in favor of #99
