### ISSUE TITLE
TODO: create administration for charitable organizations

### ISSUE THREAD

**Issue by jwo** [sketch-city/harvey-api#40]
Following same UI patterns as needs and shelters and products, create a UI available for only admins that can edit `charitable_organizations` with the fields in #39

**Comment by dorton** [comment]
@jwo @ironcoconut do we want to keep the idea of creating drafts consistent here too? If not draft, then maybe submission from a user who does not need to be admin?

**Comment by jwo** [comment]
@dorton I think maybe? But as far as I know right now, it'll be admins updating, not general public.

**Comment by dorton** [comment]
coolcool. Will follow same workflow, as it leaves it open.
