### ISSUE TITLE
Displaying UTC in date field after update

### ISSUE THREAD

**Issue by randy7771026** [sketch-city/harvey-api#62]
Just that.  User makes update then the field displays UTC.

**Comment by jwo** [comment]
Want to make sure I get it.  Keep using the RFC4339 (maybe?) format we are, but display them all in UTC rather than CT, right?

**Comment by randy7771026** [comment]
I do not think so the actual letters UTC are displayed.

**Comment by jwo** [comment]
@randy7771026 I'm sorry I'm not following. Could you expand? Maybe post a screenshot of what is happening and what you'd like to see?

**Comment by randy7771026** [comment]
OK user and I were not communicating and the problem is that after updating and going back via button at bottom it goes to page one instead of page being updated and often freezes so I will close this.
