### ISSUE TITLE
TODO - Delete Button

### ISSUE THREAD

**Issue by sya** [sketch-city/harvey-api#64]
Would like to mark something for deletion, or delete. Recently contacted by someone requesting we remove their shelter. Updated info, but would be nice to just delete the record instead. Not sure if deleting shelter name and coordinates would do it?

**Comment by jwo** [comment]
@sya admins can delete needs and shelters.

**Comment by sya** [comment]
@jwo, can you tell me how? Unless I've been removed as an Admin I do not see that functionality. For now I've added `CLOSED` to the shelter's name.

**Comment by jwo** [comment]
@dorton would you post a screenshot of how to delete?

——


- jesse

**Comment by sya** [comment]
Found how. There is an `Archive` button! Thanks

**Comment by jwo** [comment]
Yay!
