### ISSUE TITLE
UPDATED BY: Not updating name with recent editor 

### ISSUE THREAD

**Issue by sya** [sketch-city/harvey-api#65]
Updated by is not showing the name of the person that last updated the records, e.g. South Houston Intermediate. I've just updated but Tanmay is still listed as just updating.

**Comment by jwo** [comment]
@sya Did you enter in your information into the `updated_by` field? And then it didn't persist that change?

Just want to make sure I understand the issue.

**Comment by ironcoconut** [comment]
Updated by is a manual field. We are not persisting the user who last updated the record so the info is certainly incorrect. It is on the TODO list to add this functionality.

**Comment by jwo** [comment]
Closing for now. We can reopen if further info comes in. I think @ironcoconut is right on

**Comment by sya** [comment]
Got it. Right now there is no "Updated By" field in the form. In the future we may automate this, but at the moment it's hard-coded in basically. Thanks!
