### ISSUE TITLE
Add 2 fields to API Sheet to gather Cell Number and shelter manager's name

### ISSUE THREAD

**Issue by DaynaW3990** [sketch-city/harvey-api#72]
It is easier to text and ask for a shelter update than to make a phone call.  If we have a field for the cell number we can send the texts.  If we have the Manager's name, if we have to call, we can talk to an authority not a volunteer

**Comment by ironcoconut** [comment]
After discussion, we decided a private notes field is better. It should only be visible to admins.

- [ ] Private Notes (visible only to admins)
- [ ] Distribution Center (text)
- [ ] Food Pantry (text)
- [ ] Add ability to update accepting field
- [ ] Move lat and lng to bottom and add optional text
