### ISSUE TITLE
API spreadsheet Updates Needed

### ISSUE THREAD

**Issue by DaynaW3990** [sketch-city/harvey-api#78]
On the main spreadsheet, Move the name of the shelter to the third column from the beginning, after the field Accepting.

In the Shelters Update Queue, move the Show button to the front of the line.  Change it to accept or Deny.  We do not need to open to make a decision.  If we have to Open it, have the button for accept open the next shelter in the Update Queue.

Thank you for working with us.

**Comment by DaynaW3990** [comment]
In the Show form for existing Shelters, it has three buttons at the bottom.  Can they please be moved up to the top.  

Can the same three buttons be added to the UPDATE Shelters form?  We need to update their information, then archive them.  Does the Archiving save the info first then archive?  If not, can it please

**Comment by DaynaW3990** [comment]
Create a button on the main page of the Shelter's API. spreadsheet and link to these instructions

https://drive.google.com/open?id=0B6l8wQZ058Z4SXFLZG1mWTl4TUE

**Comment by tbarn** [comment]
@DaynaW3990 have you gotten a chance to check out the new "Pages" tab? We can now edit the home page, with images too. Instead of linking to instructions we can now write them there so it is all in one place.

**Comment by DaynaW3990** [comment]
I cannot see a pages tab.  can you send me a link to which site I should be looking at?  Is this the "How to use page???

If so, can I add a lot more content?

**Comment by DaynaW3990** [comment]
I'd like to put the public instructions there, but also have printable link too.  We have to be blue haired church secretary friendly...

**Comment by jwo** [comment]
@DaynaW3990 

> Can the same three buttons be added to the UPDATE Shelters form? We need to update their information, then archive them. Does the Archiving save the info first then archive? If not, can it please

We couldn't do this in the timeframe requested. You'll need to update the shelter and then click "Archive".

The rest will be live soon.
