### ISSUE TITLE
URGENT Add columns to API table

### ISSUE THREAD

**Issue by DaynaW3990** [sketch-city/harvey-api#90]
**Needed for Irma API**
Need a boolean data field for special needs shelters
Need Note field for County
Need Note field for the County's Update website
Need Time Stamp for last time the Shelter Info was updated
Need private Note field to list the name of the volunteer managing the County's info
Need a Private field for email so we can export to make a group update email
Need a Private field for Text Information So we can make a bot to send update requests

**Comment by jwo** [comment]
@DaynaW3990 

irma has forked their repo, please ask them for changes: https://github.com/Irma-Response/irma-api
